/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/club": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Club */
        get: operations["get_club_api_v1_admin_club_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Club */
        patch: operations["patch_club_api_v1_admin_club_patch"];
        trace?: never;
    };
    "/api/v1/admin/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Staff */
        get: operations["list_staff_api_v1_admin_staff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite */
        post: operations["invite_api_v1_admin_staff_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{staff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke */
        delete: operations["revoke_api_v1_admin_staff__staff_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{staff_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Roles */
        put: operations["update_roles_api_v1_admin_staff__staff_id__roles_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mobile/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mobile Login */
        post: operations["mobile_login_api_v1_auth_mobile_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mobile/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mobile Refresh */
        post: operations["mobile_refresh_api_v1_auth_mobile_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mobile/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mobile Session */
        get: operations["mobile_session_api_v1_auth_mobile_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_verify_email_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/web/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web Login */
        post: operations["web_login_api_v1_auth_web_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/web/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web Refresh */
        post: operations["web_refresh_api_v1_auth_web_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/web/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Web Session */
        get: operations["get_web_session_api_v1_auth_web_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/web/switch-club": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web Switch Club */
        post: operations["web_switch_club_api_v1_auth_web_switch_club_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_v1_invitations__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitationRequest */
        AcceptInvitationRequest: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** ClubOut */
        ClubOut: {
            /** Accent Color */
            accent_color: string;
            /** Address */
            address: string | null;
            /** City */
            city: string | null;
            /** Close Time */
            close_time: string | null;
            /** Country */
            country: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
            /** Open Time */
            open_time: string | null;
            /** Phone */
            phone: string | null;
            /** Primary Color */
            primary_color: string;
            /** Slug */
            slug: string;
            /** Sport Types */
            sport_types: components["schemas"]["Sport"][];
            /** Timezone */
            timezone: string;
            /** Website */
            website: string | null;
        };
        /**
         * ClubUpdate
         * @description Solo se modifican los campos enviados. `null` limpia los opcionales.
         */
        ClubUpdate: {
            /** Accent Color */
            accent_color?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Close Time */
            close_time?: string | null;
            /** Email */
            email?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Name */
            name?: string | null;
            /** Open Time */
            open_time?: string | null;
            /** Phone */
            phone?: string | null;
            /** Primary Color */
            primary_color?: string | null;
            /** Sport Types */
            sport_types?: components["schemas"]["Sport"][] | null;
            /** Timezone */
            timezone?: string | null;
            /** Website */
            website?: string | null;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * Gender
         * @enum {string}
         */
        Gender: "F" | "M" | "X";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvitationPreviewOut */
        InvitationPreviewOut: {
            /**
             * Account
             * @enum {string}
             */
            account: "new" | "unverified" | "existing";
            /** Club Logo Url */
            club_logo_url: string | null;
            /** Club Name */
            club_name: string;
            /** Email */
            email: string;
            /** Roles */
            roles: components["schemas"]["StaffRole"][];
        };
        /** InviteRequest */
        InviteRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Roles */
            roles: components["schemas"]["StaffRole"][];
        };
        /**
         * MembershipStatus
         * @enum {string}
         */
        MembershipStatus: "PENDING" | "APPROVED" | "REJECTED" | "INACTIVE";
        /** MembershipSummaryOut */
        MembershipSummaryOut: {
            /**
             * Club Id
             * Format: uuid
             */
            club_id: string;
            /** Club Name */
            club_name: string;
            /** Club Slug */
            club_slug: string;
            /** Logo Url */
            logo_url: string | null;
            /** Member Number */
            member_number: string | null;
            /**
             * Membership Id
             * Format: uuid
             */
            membership_id: string;
            /** Primary Color */
            primary_color: string;
            status: components["schemas"]["MembershipStatus"];
        };
        /** MobileLoginRequest */
        MobileLoginRequest: {
            /** Identifier */
            identifier: string;
            /** Password */
            password: string;
        };
        /** MobileProfileOut */
        MobileProfileOut: {
            /** Memberships */
            memberships: components["schemas"]["MembershipSummaryOut"][];
            user: components["schemas"]["UserOut"];
        };
        /** MobileSessionOut */
        MobileSessionOut: {
            /** Access Token */
            access_token: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipSummaryOut"][];
            /** Refresh Token */
            refresh_token: string;
            user: components["schemas"]["UserOut"];
        };
        /** MobileTokensOut */
        MobileTokensOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "dashboard:operations" | "dashboard:finance" | "courts:read" | "courts:write" | "reservations:read" | "reservations:write" | "members:read" | "members:write" | "members:export" | "plans:write" | "stock:read" | "stock:write" | "expenses:read" | "expenses:write" | "cash:read" | "cash:write" | "fees:read" | "fees:write" | "news:read" | "news:write" | "settings:read" | "settings:write" | "staff:manage";
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Dni */
            dni?: string | null;
            /** First Name */
            first_name?: string | null;
            gender?: components["schemas"]["Gender"] | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Birth Date */
            birth_date?: string | null;
            /** Dni */
            dni?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            gender?: components["schemas"]["Gender"] | null;
            /** Last Name */
            last_name: string;
            /** Password */
            password: string;
            /** Phone */
            phone?: string | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /** RolesUpdate */
        RolesUpdate: {
            /** Roles */
            roles: components["schemas"]["StaffRole"][];
        };
        /**
         * Sport
         * @enum {string}
         */
        Sport: "tennis" | "padel" | "football" | "basketball" | "hockey" | "volleyball" | "rugby" | "other";
        /** StaffClubOut */
        StaffClubOut: {
            /** Accent Color */
            accent_color: string;
            /**
             * Club Id
             * Format: uuid
             */
            club_id: string;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
            /** Primary Color */
            primary_color: string;
            /** Roles */
            roles: components["schemas"]["StaffRole"][];
            /** Slug */
            slug: string;
        };
        /** StaffMemberOut */
        StaffMemberOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Self */
            is_self: boolean;
            /** Roles */
            roles: components["schemas"]["StaffRole"][];
            status: components["schemas"]["StaffStatus"];
        };
        /**
         * StaffRole
         * @enum {string}
         */
        StaffRole: "OWNER" | "RESERVATIONS_MANAGER" | "STOCK_MANAGER";
        /**
         * StaffStatus
         * @enum {string}
         */
        StaffStatus: "INVITED" | "ACTIVE" | "REVOKED";
        /** SwitchClubRequest */
        SwitchClubRequest: {
            /**
             * Club Id
             * Format: uuid
             */
            club_id: string;
        };
        /** TokenRequest */
        TokenRequest: {
            /** Token */
            token: string;
        };
        /** UserOut */
        UserOut: {
            /** Avatar Url */
            avatar_url: string | null;
            /** Birth Date */
            birth_date: string | null;
            /** Dni */
            dni: string | null;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** First Name */
            first_name: string;
            gender: components["schemas"]["Gender"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Name */
            last_name: string;
            /** Phone */
            phone: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WebLoginRequest */
        WebLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * WebSessionOut
         * @description Estado de la sesión del panel. El token viaja en cookies HttpOnly, no en el body.
         */
        WebSessionOut: {
            active_club: components["schemas"]["StaffClubOut"];
            /** Clubs */
            clubs: components["schemas"]["StaffClubOut"][];
            /** Permissions */
            permissions: components["schemas"]["Permission"][];
            user: components["schemas"]["UserOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AcceptInvitationRequest = components['schemas']['AcceptInvitationRequest'];
export type ClubOut = components['schemas']['ClubOut'];
export type ClubUpdate = components['schemas']['ClubUpdate'];
export type ForgotPasswordRequest = components['schemas']['ForgotPasswordRequest'];
export type Gender = components['schemas']['Gender'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type InvitationPreviewOut = components['schemas']['InvitationPreviewOut'];
export type InviteRequest = components['schemas']['InviteRequest'];
export type MembershipStatus = components['schemas']['MembershipStatus'];
export type MembershipSummaryOut = components['schemas']['MembershipSummaryOut'];
export type MobileLoginRequest = components['schemas']['MobileLoginRequest'];
export type MobileProfileOut = components['schemas']['MobileProfileOut'];
export type MobileSessionOut = components['schemas']['MobileSessionOut'];
export type MobileTokensOut = components['schemas']['MobileTokensOut'];
export type PasswordChange = components['schemas']['PasswordChange'];
export type Permission = components['schemas']['Permission'];
export type ProfileUpdate = components['schemas']['ProfileUpdate'];
export type RefreshRequest = components['schemas']['RefreshRequest'];
export type RegisterRequest = components['schemas']['RegisterRequest'];
export type ResetPasswordRequest = components['schemas']['ResetPasswordRequest'];
export type RolesUpdate = components['schemas']['RolesUpdate'];
export type Sport = components['schemas']['Sport'];
export type StaffClubOut = components['schemas']['StaffClubOut'];
export type StaffMemberOut = components['schemas']['StaffMemberOut'];
export type StaffRole = components['schemas']['StaffRole'];
export type StaffStatus = components['schemas']['StaffStatus'];
export type SwitchClubRequest = components['schemas']['SwitchClubRequest'];
export type TokenRequest = components['schemas']['TokenRequest'];
export type UserOut = components['schemas']['UserOut'];
export type ValidationError = components['schemas']['ValidationError'];
export type WebLoginRequest = components['schemas']['WebLoginRequest'];
export type WebSessionOut = components['schemas']['WebSessionOut'];
export type $defs = Record<string, never>;
export interface operations {
    get_club_api_v1_admin_club_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubOut"];
                };
            };
        };
    };
    patch_club_api_v1_admin_club_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClubUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_staff_api_v1_admin_staff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMemberOut"][];
                };
            };
        };
    };
    invite_api_v1_admin_staff_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_v1_admin_staff__staff_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_roles_api_v1_admin_staff__staff_id__roles_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mobile_login_api_v1_auth_mobile_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MobileLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mobile_refresh_api_v1_auth_mobile_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileTokensOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mobile_session_api_v1_auth_mobile_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileProfileOut"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_verify_email_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    web_login_api_v1_auth_web_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    web_refresh_api_v1_auth_web_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSessionOut"];
                };
            };
        };
    };
    get_web_session_api_v1_auth_web_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSessionOut"];
                };
            };
        };
    };
    web_switch_club_api_v1_auth_web_switch_club_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchClubRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_api_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_invitations__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_profile_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
