"""Gastos: acción recomendada por el LLM, batch en curso e índice de explicaciones pendientes.

Revision ID: 61f74649d3b4
Revises: b005996bf352
Create Date: 2026-10-06 04:54:40.021578+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '61f74649d3b4'
down_revision: str | None = 'b005996bf352'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('anomaly_recommended_action', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('anomaly_batch_id', sa.String(length=100), nullable=True))
    op.create_index('ix_expenses_pending_explanation', 'expenses', ['club_id'], unique=False, postgresql_where=sa.text("deleted_at IS NULL AND anomaly_explained_at IS NULL AND anomaly_severity IN ('medium', 'high', 'critical')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_pending_explanation', table_name='expenses', postgresql_where=sa.text("deleted_at IS NULL AND anomaly_explained_at IS NULL AND anomaly_severity IN ('medium', 'high', 'critical')"))
    op.drop_column('expenses', 'anomaly_batch_id')
    op.drop_column('expenses', 'anomaly_recommended_action')
    # ### end Alembic commands ###
