"""Esquema inicial: tablas, RLS por tenant y permisos del rol de la aplicación.

Revision ID: b005996bf352
Revises: 
Create Date: 2026-10-06 04:35:58.507307+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings
from app.models import TENANT_TABLES
revision: str = 'b005996bf352'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport_types', sa.ARRAY(sa.String(length=20)), server_default='{}', nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), server_default='#111827', nullable=False),
    sa.Column('accent_color', sa.String(length=7), server_default='#3B82F6', nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), server_default='AR', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='America/Argentina/Buenos_Aires', nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('plan', sa.String(length=50), server_default='starter', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("accent_color ~ '^#[0-9A-Fa-f]{6}$'", name=op.f('ck_clubs_accent_color_hex')),
    sa.CheckConstraint("primary_color ~ '^#[0-9A-Fa-f]{6}$'", name=op.f('ck_clubs_primary_color_hex')),
    sa.CheckConstraint("sport_types <@ ARRAY['tennis', 'padel', 'football', 'basketball', 'hockey', 'volleyball', 'rugby', 'other']::varchar[]", name=op.f('ck_clubs_sport_types')),
    sa.CheckConstraint('open_time IS NULL OR close_time IS NULL OR open_time < close_time', name=op.f('ck_clubs_hours')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs')),
    sa.UniqueConstraint('slug', name=op.f('uq_clubs_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('F', 'M', 'X', name='gender', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('dni', name=op.f('uq_users_dni')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('active_club_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['active_club_id'], ['clubs.id'], name=op.f('fk_auth_sessions_active_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_index(op.f('ix_auth_sessions_family_id'), 'auth_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('club_news',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_news_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_club_news_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_news'))
    )
    op.create_index('ix_club_news_club_created', 'club_news', ['club_id', 'created_at'], unique=False)
    op.create_table('club_staff',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'REVOKED', name='staff_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("roles <@ ARRAY['OWNER', 'RESERVATIONS_MANAGER', 'STOCK_MANAGER']::varchar[]", name=op.f('ck_club_staff_roles_valid')),
    sa.CheckConstraint('cardinality(roles) >= 1', name=op.f('ck_club_staff_roles_not_empty')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_club_staff_email_lowercase')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_staff_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_club_staff_invited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_staff_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_staff')),
    sa.UniqueConstraint('club_id', 'email', name=op.f('uq_club_staff_club_id_email'))
    )
    op.create_index(op.f('ix_club_staff_club_id'), 'club_staff', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_staff_user_id'), 'club_staff', ['user_id'], unique=False)
    op.create_table('courts',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.Enum('tennis', 'padel', 'football', 'basketball', 'hockey', 'volleyball', 'rugby', 'other', name='sport', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('surface', sa.Enum('clay', 'hard', 'grass', 'synthetic', 'wood', 'concrete', 'other', name='court_surface', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='4', nullable=False),
    sa.Column('price_member', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_guest', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_courts_capacity_positive')),
    sa.CheckConstraint('price_member >= 0 AND price_guest >= 0', name=op.f('ck_courts_prices_non_negative')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_courts_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courts')),
    sa.UniqueConstraint('club_id', 'name', name=op.f('uq_courts_club_id_name')),
    sa.UniqueConstraint('id', 'club_id', name=op.f('uq_courts_id_club_id'))
    )
    op.create_index(op.f('ix_courts_club_id'), 'courts', ['club_id'], unique=False)
    op.create_table('expenses',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('maintenance', 'utilities', 'salaries', 'equipment', 'marketing', 'supplies', 'other', name='expense_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='ARS', nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_tax_id', sa.String(length=50), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('anomaly_severity', sa.Enum('low', 'medium', 'high', 'critical', name='anomaly_severity', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('anomaly_reasons', sa.Text(), nullable=True),
    sa.Column('anomaly_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anomaly_explanation', sa.Text(), nullable=True),
    sa.Column('anomaly_explained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.CheckConstraint('anomaly_score IS NULL OR (anomaly_score >= 0 AND anomaly_score <= 1)', name=op.f('ck_expenses_anomaly_score_range')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_expenses_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_expenses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_expenses_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_club_category', 'expenses', ['club_id', 'category'], unique=False)
    op.create_index('ix_expenses_club_date', 'expenses', ['club_id', 'expense_date'], unique=False)
    op.create_table('membership_plans',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monthly_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monthly_fee >= 0', name=op.f('ck_membership_plans_fee_non_negative')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_membership_plans_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_plans')),
    sa.UniqueConstraint('club_id', 'name', name=op.f('uq_membership_plans_club_id_name')),
    sa.UniqueConstraint('id', 'club_id', name=op.f('uq_membership_plans_id_club_id'))
    )
    op.create_index(op.f('ix_membership_plans_club_id'), 'membership_plans', ['club_id'], unique=False)
    op.create_table('one_time_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('VERIFY_EMAIL', 'RESET_PASSWORD', name='one_time_token_purpose', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_one_time_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_one_time_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_one_time_tokens_token_hash'))
    )
    op.create_index(op.f('ix_one_time_tokens_user_id'), 'one_time_tokens', ['user_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.Enum('unit', 'box', 'kg', 'liter', 'pack', name='stock_unit', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_quantity >= 0', name=op.f('ck_stock_items_min_quantity_non_negative')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_stock_items_quantity_non_negative')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_stock_items_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_items')),
    sa.UniqueConstraint('id', 'club_id', name=op.f('uq_stock_items_id_club_id'))
    )
    op.create_index('ix_stock_items_club', 'stock_items', ['club_id'], unique=False)
    op.create_table('club_memberships',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'INACTIVE', name='membership_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('member_number', sa.String(length=50), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_memberships_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_club_memberships_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id', 'club_id'], ['membership_plans.id', 'membership_plans.club_id'], name='fk_club_memberships_plan_same_club'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_memberships')),
    sa.UniqueConstraint('club_id', 'member_number', name=op.f('uq_club_memberships_club_id_member_number')),
    sa.UniqueConstraint('club_id', 'user_id', name=op.f('uq_club_memberships_club_id_user_id')),
    sa.UniqueConstraint('id', 'club_id', name=op.f('uq_club_memberships_id_club_id'))
    )
    op.create_index(op.f('ix_club_memberships_club_id'), 'club_memberships', ['club_id'], unique=False)
    op.create_index('ix_club_memberships_club_status', 'club_memberships', ['club_id', 'status'], unique=False)
    op.create_index(op.f('ix_club_memberships_user_id'), 'club_memberships', ['user_id'], unique=False)
    op.create_table('reservations',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('customer_type', sa.Enum('MEMBER', 'GUEST', name='customer_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=True),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='reservation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('APP', 'PANEL', name='reservation_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.UUID(), nullable=True),
    sa.Column('cancel_reason', sa.Enum('BY_STAFF', 'BY_MEMBER', 'EXPIRED_UNCONFIRMED', name='cancel_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('court_id'), '='), (sa.text("tstzrange(starts_at, ends_at, '[)')"), '&&'), where=sa.text("status IN ('pending', 'confirmed')"), using='gist', name='no_overlap'),
    sa.CheckConstraint("(customer_type = 'MEMBER' AND user_id IS NOT NULL) OR (customer_type = 'GUEST' AND guest_name IS NOT NULL)", name=op.f('ck_reservations_customer')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_reservations_time_range')),
    sa.CheckConstraint('total_price >= 0', name=op.f('ck_reservations_price_non_negative')),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_reservations_cancelled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_reservations_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id', 'club_id'], ['courts.id', 'courts.club_id'], name='fk_reservations_court_same_club'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reservations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reservations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('id', 'club_id', name=op.f('uq_reservations_id_club_id'))
    )
    op.create_index('ix_reservations_club_starts', 'reservations', ['club_id', 'starts_at'], unique=False)
    op.create_index('ix_reservations_court_starts', 'reservations', ['court_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('IN', 'OUT', 'ADJUSTMENT', name='stock_movement_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_before', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity_after = quantity_before + quantity_delta', name=op.f('ck_stock_movements_consistent')),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_stock_movements_delta_not_zero')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_stock_movements_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id', 'club_id'], ['stock_items.id', 'stock_items.club_id'], name='fk_stock_movements_item_same_club'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_stock_movements_performed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index('ix_stock_movements_item_created', 'stock_movements', ['item_id', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'OUTFLOW', name='transaction_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'MERCADOPAGO', name='payment_method', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_payments_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id', 'club_id'], ['club_memberships.id', 'club_memberships.club_id'], name='fk_payments_membership_same_club'),
    sa.ForeignKeyConstraint(['reservation_id', 'club_id'], ['reservations.id', 'reservations.club_id'], name='fk_payments_reservation_same_club'),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], name=op.f('fk_payments_voided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('id', 'club_id', name=op.f('uq_payments_id_club_id'))
    )
    op.create_index('ix_payments_club_occurred', 'payments', ['club_id', 'occurred_at'], unique=False)
    op.create_index('ix_payments_reservation', 'payments', ['reservation_id'], unique=False)
    op.create_table('membership_fees',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='fee_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'PAID') = (payment_id IS NOT NULL)", name=op.f('ck_membership_fees_paid_has_payment')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_membership_fees_amount_non_negative')),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_membership_fees_month_range')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_membership_fees_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id', 'club_id'], ['club_memberships.id', 'club_memberships.club_id'], name='fk_membership_fees_membership_same_club', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id', 'club_id'], ['payments.id', 'payments.club_id'], name='fk_membership_fees_payment_same_club'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_fees')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_membership_fees_payment_id'))
    )
    op.create_index('ix_membership_fees_club_period', 'membership_fees', ['club_id', 'year', 'month'], unique=False)
    op.create_index('uq_membership_fees_period_active', 'membership_fees', ['membership_id', 'year', 'month'], unique=True, postgresql_where=sa.text("status <> 'CANCELLED'"))
    # ### end Alembic commands ###
    _create_rls()


def _create_rls() -> None:
    app_role = _app_role()
    # Funciones que leen el contexto fijado por la app con set_config(..., true).
    for name, setting, kind in (
        ("app_current_user_id", "app.user_id", "uuid"),
        ("app_current_club_id", "app.club_id", "uuid"),
        ("app_current_user_email", "app.user_email", "text"),
    ):
        op.execute(
            f"CREATE FUNCTION {name}() RETURNS {kind} LANGUAGE sql STABLE AS"
            f" $$ SELECT nullif(current_setting('{setting}', true), '')::{kind} $$"
        )
    # Clubes de los que el usuario actual es socio aprobado. SECURITY DEFINER para que
    # las políticas de otras tablas puedan consultarlo sin recursión de RLS.
    op.execute("""
        CREATE FUNCTION app_member_club_ids() RETURNS SETOF uuid
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
        $$ SELECT club_id FROM club_memberships
           WHERE user_id = app_current_user_id() AND status = 'APPROVED' $$
    """)
    op.execute("REVOKE ALL ON FUNCTION app_member_club_ids() FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION app_member_club_ids() TO {app_role}")

    tenant_read = "club_id = app_current_club_id()"
    write_check = "club_id = app_current_club_id()"
    extra_read = {
        # Lo propio del usuario se ve aunque no haya club activo (login, app mobile).
        "club_staff": "user_id = app_current_user_id() OR email = app_current_user_email()",
        "club_memberships": "user_id = app_current_user_id()",
        "reservations": "user_id = app_current_user_id()",
        # Lo publicable de los clubes donde el usuario es socio aprobado.
        "courts": "club_id IN (SELECT app_member_club_ids())",
        "membership_plans": "club_id IN (SELECT app_member_club_ids())",
        "club_news": "club_id IN (SELECT app_member_club_ids())",
    }
    for table in TENANT_TABLES:
        read = tenant_read + (f" OR {extra_read[table]}" if table in extra_read else "")
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_select ON {table} FOR SELECT USING ({read})")
        op.execute(f"CREATE POLICY tenant_insert ON {table} FOR INSERT WITH CHECK ({write_check})")
        op.execute(
            f"CREATE POLICY tenant_update ON {table} FOR UPDATE"
            f" USING ({tenant_read}) WITH CHECK ({write_check})"
        )
        op.execute(f"CREATE POLICY tenant_delete ON {table} FOR DELETE USING ({tenant_read})")

    # Clubes: directorio público de lectura; solo se modifica el club activo.
    op.execute("ALTER TABLE clubs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE clubs FORCE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY clubs_select ON clubs FOR SELECT USING (true)")
    op.execute(
        "CREATE POLICY clubs_update ON clubs FOR UPDATE"
        " USING (id = app_current_club_id()) WITH CHECK (id = app_current_club_id())"
    )

    # El rol de la app solo hace DML. Los clubes se crean con scripts (rol dueño).
    op.execute(f"GRANT USAGE ON SCHEMA public TO {app_role}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {app_role}")
    op.execute(f"REVOKE INSERT, DELETE ON clubs FROM {app_role}")
    op.execute(f"REVOKE ALL ON alembic_version FROM {app_role}")


def _app_role() -> str:
    role = get_settings().DB_APP_ROLE
    if not role.replace("_", "").isalnum():
        raise ValueError(f"DB_APP_ROLE inválido: {role!r}")
    return role


def downgrade() -> None:
    op.execute(f"REVOKE ALL ON ALL TABLES IN SCHEMA public FROM {_app_role()}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_membership_fees_period_active', table_name='membership_fees', postgresql_where=sa.text("status <> 'CANCELLED'"))
    op.drop_index('ix_membership_fees_club_period', table_name='membership_fees')
    op.drop_table('membership_fees')
    op.drop_index('ix_payments_reservation', table_name='payments')
    op.drop_index('ix_payments_club_occurred', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_stock_movements_item_created', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index('ix_reservations_court_starts', table_name='reservations')
    op.drop_index('ix_reservations_club_starts', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_club_memberships_user_id'), table_name='club_memberships')
    op.drop_index('ix_club_memberships_club_status', table_name='club_memberships')
    op.drop_index(op.f('ix_club_memberships_club_id'), table_name='club_memberships')
    op.drop_table('club_memberships')
    op.drop_index('ix_stock_items_club', table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_one_time_tokens_user_id'), table_name='one_time_tokens')
    op.drop_table('one_time_tokens')
    op.drop_index(op.f('ix_membership_plans_club_id'), table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index('ix_expenses_club_date', table_name='expenses')
    op.drop_index('ix_expenses_club_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_courts_club_id'), table_name='courts')
    op.drop_table('courts')
    op.drop_index(op.f('ix_club_staff_user_id'), table_name='club_staff')
    op.drop_index(op.f('ix_club_staff_club_id'), table_name='club_staff')
    op.drop_table('club_staff')
    op.drop_index('ix_club_news_club_created', table_name='club_news')
    op.drop_table('club_news')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_family_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('clubs')
    # ### end Alembic commands ###
    op.execute(
        "DROP FUNCTION IF EXISTS app_member_club_ids(), app_current_user_id(),"
        " app_current_club_id(), app_current_user_email()"
    )
